before_script:
  - wget https://github.com/spf13/hugo/releases/download/v0.16/hugo_0.16_linux-64bit.tgz
  - echo "37ee91ab3469afbf7602a091d466dfa5  hugo_0.16_linux-64bit.tgz" | md5sum -c
  - tar xf hugo_0.16_linux-64bit.tgz
  - ./hugo version

push_to_do:
  only:
    - master
  script:
    - ./hugo
    - mkdir -p /var/www/.blog.iammiller.com
    - cp -r public/* /var/www/.blog.iammiller.com
    - cd /var/www/
