before_script:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.31/hugo_0.31_Linux-64bit.tar.gz
  - echo "1f757f65796aeaa01d5121aa66388f1c  hugo_0.31_Linux-64bit.tar.gz" | md5sum -c
  - tar xf hugo_0.31_Linux-64bit.tar.gz
  - ./hugo version

push_to_do:
  only:
    - master
  script:
    - ./hugo
    - mkdir -p /var/www/.blog.iammiller.com
    - cp -r public/* /var/www/.blog.iammiller.com
    - cd /var/www/
    - rm -rf blog.iammiller.com
    - mv .blog.iammiller.com blog.iammiller.com
