before_script:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.36.1/hugo_0.36.1_Linux-64bit.tar.gz
  - echo "640d9be133d0ea7caa617727df7565bb hugo_0.36.1_Linux-64bit.tar.gz" | md5sum -c
  - tar xf hugo_0.36.1_Linux-64bit.tar.gz
  - ./hugo version

push_to_do:
  only:
    - master
  script:
    - ./hugo
    - mkdir -p /var/www/.blog.iammiller.com
    - cp -r public/* /var/www/.blog.iammiller.com
    - cd /var/www/
    - rm -rf blog.iammiller.com
    - mv .blog.iammiller.com blog.iammiller.com
