baseurl: "https://blog.millerti.me"
languageCode: "en-us"
title: "I Am Miller's Blog"
theme: "hyde-x"
paginate: 10

author:
  name: "Matthew Miller"

permalinks:
  post: "/:year/:month/:day/:title/"

rssLink: "index.xml"

taxonomies:
  # Optional. Use if you want tags and lists.
  category: "categories"
  tag: "tags"

params:
  home: "Home"
  # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
  theme: "theme-base-0b"
  tagline: "Notes for my future self"
  customCSS: "/blog.css"

  highlight: "tomorrow-night"

  # Metadata used to drive integrations.
  gravatarHash: "50bcabd848a0f4072d21f3c75fb14dc8"

  # URL to my homepage
  personalSiteURL: "https://millerti.me"

  # Social Links
  github: "https://github.com/MasterKale/"
  stackOverflow: "https://stackoverflow.com/users/2133271/iamkale"
  twitter: "https://twitter.com/IAmKale"

  # Enable a good ol' RSS feed
  rss: true

  defaultKeywords: 'python,javascript,programming,coding'

menu:
  main:
    - name: "Categories"
      identifier: "categories"
      url: "/categories/"
      weight: 100
