baseurl = "/"
languageCode = "en-us"
title = "I Am Miller's Blog"
theme = "hyde-x"
disqusShortname = "i-am-millers-blog"
paginate = 10

[author]
    name = "Matthew Miller"

[permalinks]
    post = "/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"
    tag = "tags"

[params]
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-0b"
    tagline = "Oh man, how did I do that before...?"
    customCSS = "/blog.css"

    highlight = "tomorrow-night"

    # Metadata used to drive integrations.
    googleAnalytics = "UA-75801445-2"
    gravatarHash = "50bcabd848a0f4072d21f3c75fb14dc8"

    # Social Links
    github = "https://github.com/MasterKale/"
    stackOverflow = "http://stackoverflow.com/users/2133271/iamkale"

    # Enable a good ol' RSS feed
    rss = true

    defaultKeywords = 'python,programming,coding'
